version: 2.1

workflows:
  test_concurrency:
    triggers:
      - schedule:
          cron: "*/1 * * * *"  # Every 1 minute
          filters:
            branches:
              only: main
    jobs:
      - simulate_lengthy_process

    # ✅ concurrency must go INSIDE the named workflow, not at the top level
    concurrency:
      group: test-concurrency-demo
      cancel-in-progress: true

jobs:
  simulate_lengthy_process:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Start
          command: echo "Job started at $(date)"
      - run:
          name: Sleep for 90s
          command: |
            echo "Sleeping for 90s..."
            sleep 90
      - run:
          name: Done
          command: echo "Job finished at $(date)"

