version: 2.1

jobs:
  test_forceful_timeout:
    docker:
      - image: cimg/base:2024.01
    steps:
      # Timeout Watchdog (30s)
      - run:
          name: "⏰ Timeout Monitor (30s)"
          background: true
          command: |
            sleep 30
            echo "❌ Job timed out after 30 seconds!" > /tmp/timeout_flag
            exit 1

      # Main task (checks for timeout)
      - run:
          name: "Long-running task (60s)"
          command: |
            for i in {1..60}; do
              if [ -f /tmp/timeout_flag ]; then
                echo "Timeout detected! Killing job..."
                exit 1
              fi
              sleep 1
              echo "Working... $i/60"
            done

      # Cleanup (only runs if no timeout)
      - run:
          name: "Success"
          command: echo "✅ Completed successfully"

workflows:
  test:
    jobs:
      - test_forceful_timeout
